version: '2'
services:
  db:
    image: postgres:9.5
    container_name: db
    volumes:
     - /mnt/pgdata:/var/lib/postgresql/data
    environment:
     - TZ=Australia/Brisbane
  cache:
    build: ontocache
    container_name: ontocache
    depends_on:
      - ontoserver
    ports:
      - "8080:80"
#      - "8443:443"
    environment:
      - TZ=Australia/Brisbane
  ontoserver:
    image: aehrc/ontoserver:ctsa-5.7
    container_name: ontoserver
    depends_on:
     - db
    environment:
      - ONTOSERVER_INSECURE=true
      - ontoserver.fhir.base=https://your.domain.here/myfhir
      - authentication.oauth.endpoint.client_id.0=YOUR_NCTS_CLIENT_ID
      - authentication.oauth.endpoint.client_secret.0=YOUR_NCTS_CLIENT_SECRET
      - JAVA_OPTS=-Xmx8G
      - TZ=Australia/Brisbane
    volumes:
     - /mnt/onto:/var/onto
    logging:
      options:
        max-size: 1024m
