version: '3'
services:
  db:
    image: postgres:9.5
    volumes:
     - /mnt/pgdata:/var/lib/postgresql/data
    environment:
     - TZ=Australia/Brisbane
  cache:
    build: ontocache
    image: 127.0.0.1:5000/ontocache
    depends_on:
      - stateful
      - stateless
    ports:
      - "8080:80"
    environment:
      - TZ=Australia/Brisbane
  stateful:
    image: aehrc/ontoserver:ctsa-5.1
    depends_on:
     - db
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - ONTOSERVER_INSECURE=true
      - atom.syndication.publish.enabled=true
      - ontoserver.fhir.base=http://localhost:8080/fhir
      - ontoserver.synd.base=http://localhost:8080/synd
      - JAVA_OPTS=-Xmx1G
      - TZ=Australia/Brisbane
    volumes:
     - /mnt/onto:/var/onto
    logging:
      options:
        max-size: 1024m
  stateless:
    image: aehrc/ontoserver:ctsa-5.1
    depends_on:
     - db
     - stateful
    deploy:
      mode: replicated
      replicas: 0
    environment:
      - ONTOSERVER_INSECURE=true
      - atom.syndication.publish.enabled=true
      - ontoserver.fhir.base=http://localhost:8080/fhir
      - ontoserver.synd.base=http://localhost:8080/synd
      - ontoserver.security.enabled=true
      - ontoserver.security.readOnly.api=true
      - ontoserver.security.readOnly.fhir=true
      - ontoserver.security.readOnly.synd=true
      - JAVA_OPTS=-Xmx1G
      - TZ=Australia/Brisbane
    volumes:
     - /mnt/onto:/var/onto
    logging:
      options:
        max-size: 1024m
